### ISSUE TITLE
animation style have bug in ol3 debug.js mode

### ISSUE THREAD

**Issue by kping** [Viglino/ol3-ext#18]
map.featureanimation.path.html  is not work right in ol3 debug mode  ,like version 3.16.0 or 3.19.1 

console error is :
Uncaught TypeError: Cannot read property 'width' of null(…)

source code position:
ol.style.Shadow.prototype.render_ = function() 
{	
	var radius = this.radius_;
	
	var canvas = this.getImage();
	# var s = [canvas.width, canvas.height];

![1](https://cloud.githubusercontent.com/assets/13223165/21085478/9dfa28c6-c04d-11e6-840c-ed26dde643b0.png)

**Comment by Viglino** [comment]
Hello, 

The bug is not on the animation but concerned the shadow style that override a native function (render_ that is not exported in the release mode). Changing line 33 and 40 of `style/shadowstyle.js` from `render_` to `renderShadow_` will solve the bug.
I will change it in the next commit.

```javascript
33	this.renderShadow_();
34 };
35 ol.inherits(ol.style.Shadow, ol.style.RegularShape);
36
37 /**
38 * @private
39 */
40 ol.style.Shadow.prototype.renderShadow_ = function() 
```
Thanks for the report.

**Comment by kping** [comment]
hi, man:
It works! thank you very much.
