### ISSUE TITLE
Possibility to disable layer ordering for base maps

### ISSUE THREAD

**Issue by dirkschneemann** [Viglino/ol3-ext#2]
Hi,
this is really impressive work, thank you very much for sharing this!

I've got a question related to the layer switcher extension.
Since only one base map can be visible at the same time (because only one radio button can be checked), I do not see any meaning in specifying the layer order for base layers. However, for overlay layers, this makes perfectly sense.

How about a possibility to show/hide the layer ordering arrows per layer group or disable them for base maps altogether? Less buttons without meaningful functionality means a less cluttered view for the user.

Or is this already implemented somewhere and I overlooked it?
Cheers

**Comment by Viglino** [comment]
Hi,

Actually, "baselayer" is not the good word as it is not a layer at the background of the map. This means other non base layers may move above or below this layers...
In the example as they are all together in a group the reordering arrow are not usefull and you can remove them with css :
```
.ol-layerswitcher ul ul .layerup, .ol-layerswitcher ul ul .layerdown {
    display: none;
}
```

But this means all layers in a group would also loose their arrows...

An other possibility would be to add a "baselayer" class to the baselayer of the list to allow css's customisation.
```
.ol-layerswitcher li.baselayer .layerup, .ol-layerswitcher li.baselayer .layerdown {
    display: none;
}
```

An other solution is to have real baselayer, allways on background or to have fixed layer that can not move...

Cheers

**Comment by dirkschneemann** [comment]
Hi,
sorry for the late feedback :-/
Thank you for your suggestions. The second possibility (adding a "baselayer" class to the list elements) works fine for me when I set it directly in the browser's console.
However, do you know how I can set this programatically for all base layers (all layers where I set the "baseLayer: true" option in the constructor)?

Cheers

**Comment by Viglino** [comment]
Hi,
That's the right way to do. I'll add it to the next commit.
@+

**Comment by Pigeo** [comment]
Hi,
The CSS `display:none;` trick does not completely address the problem, since it's still possible to move another layer under the base layer (which is obviously useless).
How would you fix that last thing?
I was thinking of having an event handler (maybe on the changelayer event?), that would check if the move is allowed or not, depending on wether the moved layer is moved over a base layer (or group of base layers), which generally occupies the first place in the list of layers (starting from the bottom), or not.
Is this possible? What should I do to inform ol-ext of wether the move is allowed or not?
