### ISSUE TITLE
can't crop layer with GeoJSON

### ISSUE THREAD

**Issue by songsgroup** [Viglino/ol3-ext#31]
In this http://viglino.github.io/ol3-ext/examples/map.filter.crop.html  file ,i changed 
`var dep` value to a GeoJSON  content [http://dataxiu.com/datas/shp/china_84.json](url),and `var coords = result.features[0].geometry.coordinates;`**there is not crop layer.** GeoJSON can load map using code `ol.format.GeoJSON()`.

**Comment by Viglino** [comment]
Hi,
The problem is not on the filter, but on the coordinate system of your GeoJSON (EPSG:4326). You have to transform it to the map. Pay attention you have a multipolygon when creating the geometry.
Look at this example for more: http://codepen.io/viglino/pen/GWBJoj
You also can use the ol.format.GeoJSON to read the GeoJSON but remember to set the dataProjection and featureProjection.

**Comment by songsgroup** [comment]
thanks very much!thanks.

**Comment by seema30fresher** [comment]
Hi,
In this http://viglino.github.io/ol3-ext/examples/map.filter.crop.html or http://viglino.github.io/ol3-ext/examples/map.filter.composite.html file ,how i add the multiple vector layers.In this http://viglino.github.io/ol3-ext/examples/map.filter.composite.html file ,if i add single layer then that layer is not cropped.I have multiple layers+layer-switching from overlay layers ,i wan't to crop some layers based on button click,help me,Thanks.
