### ISSUE TITLE
ol extend problem

### ISSUE THREAD

**Issue by dyh333** [Viglino/ol3-ext#47]
hi, @Viglino . I am trying to extend an openlayers function, but met some problems need your advice sincerely.

what I do is define an ol.source.GeoneImageArcGISRest which inherits ol.source.ImageArcGISRest, and update some little code. but I found if using the mixed ol.js, it can not work well, while using the origin debug ol.js, it seems normal.

![image](https://user-images.githubusercontent.com/1221313/29152361-a54ff9dc-7db9-11e7-8f67-b8543c80d81b.png)

here is my test page. 
[using ol.js](http://58.210.9.131/ol3-ext/examples/map.geone.dynamiclayer.html)
[using ol-debug.js](http://58.210.9.131/ol3-ext/examples/map.geone.dynamiclayer-debug.html)

and my repo in https://github.com/dyh333/ol3-ext .

would you give me some help. thanks.

**Comment by Viglino** [comment]
Hello,

The problem is that the `getRequestUrl_` is not exported in ol.js thus it can't be overriden.

You should look at the [setImageLoadFunction](https://openlayers.org/en/latest/apidoc/ol.source.ImageArcGISRest.html#setImageLoadFunction) you can pass in the options of the [source](https://openlayers.org/en/latest/apidoc/ol.source.ImageArcGISRest.html).
Using this function you can override the uri of the image.
Be aware that all internal parameters of the source are only avaliable in the debug mode (this.url_, this.image_, this.ratio_, etc.). manipulate (getUrl(), setUrl(), etc.) when they exist.

@+

**Comment by dyh333** [comment]
@Viglino  thanks!  i will try again.
